// src/components/AlertDetailModal.jsx
import React, { useState, useEffect } from "react";

const CloseIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-6 w-6">
    <line x1="18" y1="6" x2="6" y2="18"></line>
    <line x1="6" y1="6" x2="18" y2="18"></line>
  </svg>
);

const mockActionLog = [
  { id: 1, text: "Forwarded to HDFC Bank", author: "Officer A. Kumar", timestamp: "03/10/2025 13:31" },
  { id: 2, text: "Status changed to 'Acknowledged'", author: "Officer A. Kumar", timestamp: "03/10/2025 13:30" },
  { id: 3, text: "Alert generated by AI Engine", author: "System", timestamp: "03/10/2025 13:28" },
];

export default function AlertDetailModal({ alert, onClose }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [actionLog, setActionLog] = useState([]);
  const [isLoadingLog, setIsLoadingLog] = useState(true);

  useEffect(() => {
    if (alert) {
      setIsLoadingLog(true);
      const timer = setTimeout(() => {
        setActionLog(mockActionLog);
        setIsLoadingLog(false);
      }, 400);
      return () => clearTimeout(timer);
    }
  }, [alert]);

  if (!alert) return null;

  const priorityStyles = {
    Critical: "bg-red-500/80 text-red-100",
    High: "bg-orange-500/80 text-orange-100",
    Medium: "bg-yellow-500/80 text-yellow-100",
  };

  const fraudType = alert.fraudType || "N/A";
  const involvedBank = alert.involvedBank || "N/A";
  const amount = alert.amount || 0;
  const complaintIds = alert.complaintIds || [];
  const trend = alert.trend || "Rising";
  const confidenceScore = alert.confidenceScore || "N/A";
  const aiExplanation = alert.aiExplanation || "Model explanation unavailable.";

  const handleAction = async (actionType) => {
    setIsSubmitting(true);
    try {
      if (actionType === "Forward") {
        // Import the service dynamically to avoid circular dependencies
        const { forwardAlertToBank } = await import("../services/bankAlertService");
        await forwardAlertToBank(alert);
        console.log(`Alert ${alert.id} forwarded to bank successfully`);
        alert("✅ Alert successfully forwarded to bank!");
      } else {
        await new Promise((resolve) => setTimeout(resolve, 800));
        console.log(`Action ${actionType} executed for alert ${alert.id}`);
      }
      onClose();
    } catch (err) {
      console.error("Error executing action:", err);
      alert("❌ Failed to forward alert. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[2000]">
      <div className="bg-[#0a1931] border border-blue-800 rounded-lg shadow-2xl w-full max-w-4xl text-white flex flex-col">
        {/* header */}
        <header className="flex items-center justify-between p-4 border-b border-blue-900/50">
          <div className="flex items-center gap-4">
            <div
              className={`font-bold px-4 py-1.5 rounded-md text-sm ${priorityStyles[alert.priority] || "bg-slate-500/80"
                }`}
            >
              {alert.priority} Alert
            </div>
            <h2 className="text-xl font-bold">{alert.location}</h2>
          </div>
          <button
            onClick={onClose}
            className="hover:text-red-500 disabled:opacity-50"
            disabled={isSubmitting}
          >
            <CloseIcon />
          </button>
        </header>

        {/* body */}
        <main
          className="p-6 grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4 overflow-y-auto"
          style={{ maxHeight: "75vh" }}
        >
          {/* case details */}
          <div className="flex flex-col gap-4 pr-0 md:pr-6 border-b md:border-b-0 md:border-r border-blue-900/50">
            <h3 className="text-lg font-semibold text-blue-300 border-b border-blue-300/20 pb-2">
              Case Details
            </h3>
            <div>
              <strong>Fraud Type:</strong>{" "}
              <span className="bg-gray-700 px-2 py-1 rounded-md text-sm">{fraudType}</span>
            </div>
            <div>
              <strong>Time Series Start:</strong> <span>{alert.time}</span>
            </div>
            <div>
              <strong>Involved Bank/UPI:</strong> <span>{involvedBank}</span>
            </div>
            <div>
              <strong>Estimated Loss:</strong>{" "}
              <span className="font-bold">₹{new Intl.NumberFormat("en-IN").format(amount)}</span>
            </div>
            <div>
              <h4 className="font-semibold mb-2">Complaint IDs</h4>
              <ul className="list-disc list-inside bg-black/20 p-2 rounded-md text-sm">
                {complaintIds.map((id) => (
                  <li key={id}>{id}</li>
                ))}
              </ul>
            </div>
          </div>

          {/* AI insights */}
          <div className="flex flex-col gap-4">
            <h3 className="text-lg font-semibold text-green-300 border-b border-green-300/20 pb-2">
              AI Predictive Insights
            </h3>
            <div>
              <strong>Predicted Trend:</strong> <span className="font-bold">{trend}</span>
            </div>
            <div>
              <strong>Confidence Score:</strong>{" "}
              <span className="text-2xl font-bold text-green-400">{confidenceScore}%</span>{" "}
              chance of repeat fraud in 2 hrs.
            </div>
            <div className="mt-2">
              <h4 className="font-semibold mb-1">AI Explanation</h4>
              <p className="bg-black/20 p-3 rounded-md text-gray-300 italic">
                "{aiExplanation}"
              </p>
            </div>
          </div>

          {/* action log */}
          <div className="flex flex-col gap-2 col-span-1 md:col-span-2 border-t border-blue-900/50 pt-4 mt-2">
            <h3 className="text-lg font-semibold text-gray-300">Case Action Log</h3>
            <div className="bg-black/20 p-3 rounded-md text-sm space-y-2 max-h-40 overflow-y-auto">
              {isLoadingLog ? (
                <p className="text-gray-400">Loading log...</p>
              ) : (
                actionLog.map((log) => (
                  <div
                    key={log.id}
                    className="flex justify-between items-center text-gray-300"
                  >
                    <p>• {log.text}</p>
                    <p className="text-xs text-gray-500 text-right">
                      {log.author} - {log.timestamp}
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>
        </main>

        {/* footer */}
        <footer className="p-4 border-t border-blue-900/50 flex justify-end gap-3">
          <button
            onClick={() => handleAction("Acknowledge")}
            disabled={isSubmitting}
            className="bg-blue-600 hover:bg-blue-500 disabled:bg-gray-500 disabled:cursor-not-allowed py-2 px-4 rounded-md"
          >
            {isSubmitting ? "Submitting..." : "Acknowledge"}
          </button>
          <button
            onClick={() => handleAction("Forward")}
            disabled={isSubmitting}
            className="bg-green-600 hover:bg-green-500 disabled:bg-gray-500 disabled:cursor-not-allowed py-2 px-4 rounded-md"
          >
            {isSubmitting ? "Submitting..." : "Forward to Bank"}
          </button>
        </footer>
      </div>
    </div>
  );
}
