// App.jsx (COMPLETE and CORRECTED)

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { MapContainer, TileLayer, Marker, Popup, useMap } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import axios from 'axios'; // Used for fetching inside this monolithic file

// --- API CONFIG & SERVICE ---
const API_BASE_URL = 'http://127.0.0.1:8000';

const fetchAlerts = async ({ priority_levels, limit }) => {
    const params = new URLSearchParams();
    if (priority_levels && priority_levels.length > 0) {
        priority_levels.forEach(level => params.append("priority_levels", level));
    }
    params.append("limit", limit);
    
    const url = `${API_BASE_URL}/api/alerts?${params.toString()}`;
    try {
        const response = await axios.get(url);
        return response.data;
    } catch (error) {
        console.error("Error fetching alerts:", error);
        return [];
    }
};

const fetchHotspots = async () => {
    try {
        const response = await axios.get(`${API_BASE_URL}/api/hotspots`);
        return response.data;
    } catch (error) {
        console.error("Error fetching predicted hotspots:", error);
        return [];
    }
};


// --- SVG ICONS (No changes) ---
const WarningIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-yellow-400"><path d="m21.73 18-8-14a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>;
const LiveIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" className="text-red-500"><circle cx="12" cy="12" r="10"></circle></svg>;
const CalendarIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>;
const FilterIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>;
const LocationIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-400"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>; // Corrected closing tag
const ClockIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-400"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>;
const EyeIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>;
const UserIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>;
const BellIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>;
const CloseIcon = () => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-6 w-6"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>;

// --- STATIC DATA ---
const fraudTypes = ['UPI Scam', 'ATM Skimming', 'Phishing', 'Loan App Fraud', 'Card Fraud'];
const mockActionLog = [
    { id: 1, text: "Forwarded to HDFC Bank", author: "Officer A. Kumar", timestamp: "03/10/2025 13:31" },
    { id: 2, text: "Status changed to 'Acknowledged'", author: "Officer A. Kumar", timestamp: "03/10/2025 13:30" },
    { id: 3, text: "Alert generated by AI Engine", author: "System", timestamp: "03/10/2025 13:28" },
];

// --- HELPER FUNCTION to transform API data to match component props ---
const transformAlertData = (alert) => ({
    ...alert,
    position: [alert.geo_lat, alert.geo_long],
    priority: alert.priority_level,
    location: alert.location_name,
    complaints: alert.complaint_count,
    amount: alert.total_amount,
    time: new Date(alert.last_updated).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
});


// --- CHILD COMPONENTS ---

const Header = ({ isLive, onLiveToggle }) => (
    <header className="bg-gradient-to-b from-[#032042] to-[#0951a8] text-white flex items-center justify-between px-6 py-4 shadow-lg">
        <div className="flex items-center gap-4"><img src="https://img.icons8.com/fluency/48/cyber-security.png" alt="Logo" className="h-10 w-10" /><h1 className="text-2xl font-bold tracking-wide">Cybercrime Predictive Dashboard</h1></div>
        <div onClick={onLiveToggle} className={`flex items-center gap-4 px-4 py-2 rounded-lg cursor-pointer transition-colors ${isLive ? 'bg-red-600 animate-pulse' : 'bg-black bg-opacity-20'}`}>
            <LiveIcon />
            <span className="font-semibold">Live Mode</span>
        </div>
        <div className="flex items-center gap-6"><div className="flex items-center gap-2"><CalendarIcon /><span>3 Oct 2025, 13:55</span></div><div className="h-8 w-px bg-white/30"></div><div className="relative"><BellIcon /><div className="absolute -top-2 -right-2 bg-red-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center border-2 border-[#0951a8]">15</div></div><div className="flex items-center gap-3"><div className="h-10 w-10 bg-blue-500 rounded-full flex items-center justify-center"><UserIcon /></div><div><p className="font-bold text-sm">LEA Officer</p><p className="text-xs text-gray-300">Chennai Region</p></div></div></div>
    </header>
);

const Sidebar = ({ setPriorityFilter, priorityFilter, fraudFilter, setFraudFilter }) => {
    const overviewStats = [ { label: "Today's Complaints", value: "6,262", icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path></svg> }, { label: "Critical Alerts", value: "12", icon: <WarningIcon /> }, { label: "High Alerts", value: "62", icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg> }, { label: "Medium Alerts", value: "6,052", icon: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> }, ];
    const handlePriorityChange = (e) => { const { name, checked } = e.target; setPriorityFilter(prev => ({ ...prev, [name]: checked })); };
    const handleFraudChange = (e) => { const { name, checked } = e.target; setFraudFilter(prev => ({ ...prev, [name]: checked })); };
    return (
        <aside className="bg-gradient-to-b from-[#032042] to-[#0951a8] text-white p-6 flex flex-col gap-8 overflow-y-auto">
            <div>
                <div className="flex items-center gap-3 mb-6"> <FilterIcon /> <h2 className="text-2xl font-bold">Filters</h2> </div>
                <div className="flex flex-col gap-6"><div><label className="text-sm font-semibold mb-2 block">Time Range</label><select className="w-full bg-black/30 p-3 rounded-md appearance-none"><option>Last 24 Hours</option> <option>Last 7 Days</option> <option>Last 30 Days</option></select></div><div><h3 className="text-sm font-semibold mb-3">Fraud Type</h3><div className="flex flex-col gap-3">{fraudTypes.map(type => (<label key={type} className="flex items-center gap-3 cursor-pointer"><input type="checkbox" name={type} checked={fraudFilter[type]} onChange={handleFraudChange} className="form-checkbox h-5 w-5 bg-gray-800 border-gray-600 rounded" /><span>{type}</span></label>))}</div></div><div><h3 className="text-sm font-semibold mb-3">Priority Level</h3><div className="flex flex-col gap-3"><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" name="Critical" checked={priorityFilter.Critical} onChange={handlePriorityChange} className="form-checkbox h-5 w-5 text-red-600 bg-gray-800 border-gray-600 rounded" /><span className="px-3 py-1 text-sm font-bold bg-red-500/80 rounded-md">Critical</span></label><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" name="High" checked={priorityFilter.High} onChange={handlePriorityChange} className="form-checkbox h-5 w-5 text-orange-500 bg-gray-800 border-gray-600 rounded" /><span className="px-3 py-1 text-sm font-bold bg-orange-500/80 rounded-md">High</span></label><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" name="Medium" checked={priorityFilter.Medium} onChange={handlePriorityChange} className="form-checkbox h-5 w-5 text-yellow-500 bg-gray-800 border-gray-600 rounded" /><span className="px-3 py-1 text-sm font-bold bg-yellow-500/80 rounded-md">Medium</span></label></div></div></div>
            </div>
            <div className="bg-white/5 p-4 rounded-lg mt-4">
                <h3 className="font-bold mb-4">Today's Overview</h3>
                <div className="flex flex-col gap-3">{overviewStats.map(stat => (<div key={stat.label} className="flex items-center justify-between bg-black/20 p-3 rounded-md"><div className="flex items-center gap-3"> <div className="text-blue-300">{stat.icon}</div> <span className="text-sm text-gray-300">{stat.label}</span> </div><span className="font-bold text-lg">{stat.value}</span></div>))}</div>
            </div>
        </aside>
    );
};


// --- MapDisplay Component with Hotspot rendering ---
const MapDisplay = ({ alerts, hotspots }) => { // Accepts hotspots now
    const mapRef = useRef(null);
    const mapInstance = useRef(null);
    const hotspotCircles = useRef([]);
    const initialCenter = [20.5937, 78.9629]; // Center of India
    const initialZoom = 5;

    const MapControls = () => { 
        const map = useMap(); 
        mapRef.current = map; 
        mapInstance.current = map; // Store map instance
        return null; 
    };

    const createCustomIcon = (color) => { const markerHtml = `<span style="background-color: ${color}; width: 2rem; height: 2rem; border-radius: 50% 50% 50% 0; border: 2px solid white; display: block; transform: rotate(-45deg);"></span>`; return L.divIcon({ html: markerHtml, className: 'bg-transparent', iconSize: [32, 32], iconAnchor: [16, 32], popupAnchor: [0, -32] }); };
    const iconPriority = { Critical: createCustomIcon('#EF4444'), High: createCustomIcon('#F97316'), Medium: createCustomIcon('#EAB308') };
    
    // Hotspot styling logic
    const getHotspotStyle = (riskLevel) => {
        switch (riskLevel) {
          case 'Extreme':
            return { color: '#ff0000', fillColor: '#ff0000', fillOpacity: 0.6, radius: 2000 };
          case 'High':
            return { color: '#ff8c00', fillColor: '#ff8c00', fillOpacity: 0.5, radius: 1500 };
          case 'Elevated':
            return { color: '#ffd700', fillColor: '#ffd700', fillOpacity: 0.4, radius: 1000 };
          default:
            return { color: '#00bfff', fillColor: '#00bfff', fillOpacity: 0.3, radius: 500 };
        }
      };

    const updateHotspotLayers = (map, newHotspots) => {
        hotspotCircles.current.forEach(circle => map.removeLayer(circle));
        hotspotCircles.current = [];

        newHotspots.forEach(hotspot => {
          const style = getHotspotStyle(hotspot.risk_level);
          
          const circle = L.circle([hotspot.geo_lat, hotspot.geo_long], {
            ...style,
            weight: 1,
            className: 'animate-pulse' 
          }).addTo(map);

          circle.bindPopup(
            `<b>PREDICTIVE HOTSPOT: ${hotspot.city}</b><br>` +
            `Risk Level: ${hotspot.risk_level}<br>` +
            `Risk Score: ${hotspot.risk_score.toFixed(2)}<br>` +
            `Top Fraud: ${hotspot.top_fraud_types.join(', ')}`
          );

          hotspotCircles.current.push(circle);
        });
    };
    
    const handleZoomIn = () => mapRef.current?.zoomIn();
    const handleZoomOut = () => mapRef.current?.zoomOut();
    const handleResetView = () => mapRef.current?.setView(initialCenter, initialZoom);

    // Effect to update hotspot layers when data changes
    useEffect(() => {
        if (mapInstance.current) {
            updateHotspotLayers(mapInstance.current, hotspots);
        }
    }, [hotspots]); 

    return (
        <div className="relative h-[450px] bg-gray-800 rounded-lg overflow-hidden shadow-lg">
            <MapContainer center={initialCenter} zoom={initialZoom} scrollWheelZoom={true} style={{ height: '100%', width: '100%' }} zoomControl={false}>
                <TileLayer attribution='&copy; CARTO' url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png" />
                <MapControls />
                {alerts.map(alert => (<Marker key={alert.id} position={alert.position} icon={iconPriority[alert.priority] || createCustomIcon('grey')}><Popup><div className="font-sans"><p className="font-bold text-lg">{alert.location}</p><p><strong>Priority:</strong> {alert.priority}</p></div></Popup></Marker>))}
            </MapContainer>
            <div className="absolute bottom-4 left-4 flex gap-3 z-[1000]"><button onClick={handleZoomIn} className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md shadow-md">Zoom In</button><button onClick={handleZoomOut} className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md shadow-md">Zoom Out</button><button onClick={handleResetView} className="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md shadow-md">Reset View</button></div>
            
            {/* Alert Risk Levels Legend */}
            <div className="absolute top-4 right-4 bg-black/50 p-4 rounded-lg backdrop-blur-sm text-white z-[1000]"><h4 className="font-bold mb-2">Alert Risk Levels</h4><ul className="space-y-2 text-sm"><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-red-500 border-2 border-red-300"></div>Critical</li><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-orange-500 border-2 border-orange-300"></div>High</li><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-yellow-500 border-2 border-yellow-300"></div>Medium</li></ul></div>
            
            {/* Predictive Hotspot Legend */}
            <div className="absolute top-4 right-4 translate-y-36 bg-black/50 p-4 rounded-lg backdrop-blur-sm text-white z-[1000]"><h4 className="font-bold mb-2">Predicted Hotspots</h4><ul className="space-y-2 text-sm"><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-red-600 border-2 border-red-400"></div>Extreme Risk</li><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-orange-600 border-2 border-orange-400"></div>High Risk</li><li className="flex items-center gap-2"><div className="w-4 h-4 rounded-full bg-yellow-600 border-2 border-yellow-400"></div>Elevated Risk</li></ul></div>
        </div>
    );
};

const AlertItem = ({ alert, onView }) => {
    const priorityStyles = { Critical: 'bg-red-500/80 text-red-100', High: 'bg-orange-500/80 text-orange-100', Medium: 'bg-yellow-500/80 text-yellow-100', };
    const statusStyles = { Open: 'border-blue-400 text-blue-300', Acknowledged: 'border-green-400 text-green-300', };
    const handleActionClick = (action) => { console.log(`Action: ${action} for Alert ID: ${alert.id}`); };
    return (
        <div className="p-4 bg-white/5 hover:bg-white/10 rounded-lg transition-colors duration-200 text-sm">
            <div className="grid grid-cols-[1fr_2fr_1fr_1fr_1fr_1fr_auto] items-center gap-4"><div className={`font-bold px-3 py-1 rounded-md text-center text-xs ${priorityStyles[alert.priority]}`}> {alert.priority} </div><div className="flex items-center gap-2"> <LocationIcon /> <span className="font-semibold">{alert.location}</span> </div><div className="flex items-center gap-2 text-gray-300"> <ClockIcon /> <span>{alert.time}</span> </div><div className="text-gray-300">{alert.complaints} complaints</div><div className="font-semibold text-white">₹{new Intl.NumberFormat('en-IN', { maximumSignificantDigits: 3 }).format(alert.amount / 100000)}L</div><div className={`text-center border py-1 px-3 rounded-full text-xs font-semibold ${statusStyles[alert.status]}`}> {alert.status} </div><button onClick={() => onView(alert)} className="flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-600 text-white font-semibold py-2 px-4 rounded-lg border border-slate-500"> <EyeIcon /> <span>View</span> </button></div>
            <div className="mt-3 flex justify-end items-center gap-2"><span className="text-xs font-bold text-gray-400">AI INSIGHT: {alert.ai_insight_text}</span><div className="flex gap-2"><button onClick={() => handleActionClick('Acknowledge')} className="text-xs bg-blue-600/50 hover:bg-blue-600/80 py-1 px-3 rounded-md">Acknowledge</button><button onClick={() => handleActionClick('Forward to Bank')} className="text-xs bg-green-600/50 hover:bg-green-600/80 py-1 px-3 rounded-md">Forward to Bank</button><button onClick={() => handleActionClick('Deploy Team')} className="text-xs bg-red-600/50 hover:bg-red-600/80 py-1 px-3 rounded-md">Deploy Team</button></div></div>
        </div>
    );
};

const AlertsSection = ({ alerts, onViewAlert }) => (
    <div className="mt-6"><div className="flex justify-between items-center mb-4"><div className="flex items-center gap-4"> <WarningIcon /> <h2 className="text-3xl font-bold text-white">Recent Alerts</h2> </div><button className="border border-blue-500 text-white font-bold py-2 px-5 rounded-lg hover:bg-blue-500 transition-colors">View All Alerts</button></div><div className="flex flex-col gap-3"> {alerts.map(alert => <AlertItem key={alert.id} alert={alert} onView={onViewAlert} />)} </div></div>
);

const AlertDetailModal = ({ alert, onClose }) => {
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [actionLog, setActionLog] = useState([]);
    const [isLoadingLog, setIsLoadingLog] = useState(true);
    useEffect(() => { if (alert) { setIsLoadingLog(true); const timer = setTimeout(() => { setActionLog(mockActionLog); setIsLoadingLog(false); }, 500); return () => clearTimeout(timer); } }, [alert]);
    if (!alert) return null;
    const handleAction = async (actionType) => { setIsSubmitting(true); console.log(`Executing action: ${actionType} for Alert ID: ${alert.id}`); try { const response = await new Promise(resolve => setTimeout(() => resolve({ ok: true }), 1000)); if (!response.ok) throw new Error(`API call failed for ${actionType}`); onClose(); } catch (error) { console.error(error); } finally { setIsSubmitting(false); } };
    const priorityStyles = { Critical: 'bg-red-500/80 text-red-100', High: 'bg-orange-500/80 text-orange-100', Medium: 'bg-yellow-500/80 text-yellow-100', };
    
    // Fallback for missing nested properties
    const fraudType = alert.fraudType || 'N/A';
    const involvedBank = alert.involvedBank || 'N/A';
    const amount = alert.amount || 0;
    const complaintIds = alert.complaintIds || [];
    const trend = alert.trend || 'N/A';
    const confidenceScore = alert.confidenceScore || 'N/A';
    const aiExplanation = alert.aiExplanation || 'No explanation available.';

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[2000]">
            <div className="bg-[#0a1931] border border-blue-800 rounded-lg shadow-2xl w-full max-w-4xl text-white flex flex-col">
                <header className="flex items-center justify-between p-4 border-b border-blue-900/50"><div className="flex items-center gap-4"><div className={`font-bold px-4 py-1.5 rounded-md text-sm ${priorityStyles[alert.priority]}`}>{alert.priority} Alert</div><h2 className="text-xl font-bold">{alert.location}</h2></div><button onClick={onClose} className="hover:text-red-500 disabled:opacity-50" disabled={isSubmitting}><CloseIcon/></button></header>
                <main className="p-6 grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4 overflow-y-auto" style={{maxHeight: '75vh'}}>
                    <div className="flex flex-col gap-4 pr-6 border-r border-blue-900/50"><h3 className="text-lg font-semibold text-blue-300 border-b border-blue-300/20 pb-2">Case Details</h3><div><strong>Fraud Type:</strong> <span className="bg-gray-700 px-2 py-1 rounded-md text-sm">{fraudType}</span></div><div><strong>Time Series Start:</strong> <span>{alert.time}</span></div><div><strong>Involved Bank/UPI:</strong> <span>{involvedBank}</span></div><div><strong>Estimated Loss:</strong> <span className="font-bold">₹{new Intl.NumberFormat('en-IN').format(amount)}</span></div><div><h4 className="font-semibold mb-2">Complaint IDs</h4><ul className="list-disc list-inside bg-black/20 p-2 rounded-md text-sm">{complaintIds.map(id => <li key={id}>{id}</li>)}</ul></div></div>
                    <div className="flex flex-col gap-4"><h3 className="text-lg font-semibold text-green-300 border-b border-green-300/20 pb-2">AI Predictive Insights</h3><div><strong>Predicted Trend:</strong> <span className="font-bold">{trend}</span></div><div><strong>Confidence Score:</strong> <span className="text-2xl font-bold text-green-400">{confidenceScore}%</span> chance of repeat fraud in 2 hrs.</div><div className="mt-2"><h4 className="font-semibold mb-1">AI Explanation</h4><p className="bg-black/20 p-3 rounded-md text-gray-300 italic">"{aiExplanation}"</p></div></div>
                    <div className="flex flex-col gap-2 col-span-1 md:col-span-2 border-t border-blue-900/50 pt-4 mt-2"><h3 className="text-lg font-semibold text-gray-300">Case Action Log</h3><div className="bg-black/20 p-3 rounded-md text-sm space-y-2 max-h-40 overflow-y-auto">{isLoadingLog ? (<p className="text-gray-400">Loading log...</p>) : (actionLog.map(log => (<div key={log.id} className="flex justify-between items-center text-gray-300"><p>• {log.text}</p><p className="text-xs text-gray-500 text-right">{log.author} - {log.timestamp}</p></div>)))}</div></div>
                </main>
                <footer className="p-4 border-t border-blue-900/50 flex justify-end gap-3"><button onClick={() => handleAction('Acknowledge')} disabled={isSubmitting} className="bg-blue-600 hover:bg-blue-500 disabled:bg-gray-500 disabled:cursor-not-allowed py-2 px-4 rounded-md">{isSubmitting ? 'Submitting...' : 'Acknowledge'}</button><button onClick={() => handleAction('Forward')} disabled={isSubmitting} className="bg-green-600 hover:bg-green-500 disabled:bg-gray-500 disabled:cursor-not-allowed py-2 px-4 rounded-md">{isSubmitting ? 'Submitting...' : 'Forward to Bank'}</button><button onClick={() => handleAction('Deploy')} disabled={isSubmitting} className="bg-red-600 hover:bg-red-500 disabled:bg-gray-500 disabled:cursor-not-allowed py-2 px-4 rounded-md">{isSubmitting ? 'Submitting...' : 'Deploy Team'}</button></footer>
            </div>
        </div>
    );
};

// --- MAIN DASHBOARD COMPONENT ---
export default function Dashboard() {
    const [alerts, setAlerts] = useState([]);
    const [hotspots, setHotspots] = useState([]); // NEW STATE for Hotspots
    const [loading, setLoading] = useState(true);
    const [selectedAlert, setSelectedAlert] = useState(null);
    const [isLive, setIsLive] = useState(false);
    const [priorityFilter, setPriorityFilter] = useState({ Critical: true, High: true, Medium: true });
    const [fraudFilter, setFraudFilter] = useState(fraudTypes.reduce((acc, type) => ({...acc, [type]: true}), {}));

    // REFACTORED: useCallback for fetching both Alerts and Hotspots
    const fetchData = useCallback(async (currentFilters) => {
        setLoading(true);
        const selectedPriorities = Object.keys(currentFilters.priority).filter(key => currentFilters.priority[key]);
        
        // 1. Fetch Alerts (with high limit) and Hotspots concurrently
        const [alertData, hotspotData] = await Promise.all([
            fetchAlerts({ 
                priority_levels: selectedPriorities,
                limit: 50, // FIX: Request up to 50 alerts
            }),
            fetchHotspots()
        ]);
        
        const transformedAlerts = alertData.map(transformAlertData);
        setAlerts(transformedAlerts);
        setHotspots(hotspotData); // Update Hotspot State
        setLoading(false);
    }, []);

    // Effect for initial data fetch and filter changes
    useEffect(() => {
        fetchData({ priority: priorityFilter, fraud: fraudFilter });
    }, [priorityFilter, fraudFilter, fetchData]); 

    // Effect for handling WebSocket connection
    useEffect(() => {
        if (isLive) {
            console.log("Connecting to WebSocket for live updates...");
            const ws = new WebSocket("ws://127.0.0.1:8000/api/ws/live");

            ws.onopen = () => console.log("WebSocket connection established.");
            ws.onclose = () => console.log("WebSocket connection closed.");

            ws.onmessage = (event) => {
                const newAlertData = JSON.parse(event.data);
                console.log("New live alert received:", newAlertData);
                
                // When a new live alert comes, re-run the full data fetch
                fetchData({ priority: priorityFilter, fraud: fraudFilter });
            };

            return () => ws.close();
        }
    }, [isLive, fetchData, priorityFilter, fraudFilter]); 

    if (loading && alerts.length === 0) {
        return <div className="bg-[#0f234c] min-h-screen text-white flex items-center justify-center text-2xl">Loading Dashboard Data...</div>;
    }

    return (
        <div className="bg-[#0f234c] min-h-screen text-white font-sans">
            <div className="grid grid-cols-[350px_1fr] h-screen">
                <Sidebar 
                    setPriorityFilter={setPriorityFilter} 
                    priorityFilter={priorityFilter} 
                    fraudFilter={fraudFilter} 
                    setFraudFilter={setFraudFilter} 
                />
                <main className="flex flex-col h-screen">
                    <Header isLive={isLive} onLiveToggle={() => setIsLive(!isLive)} />
                    <div className="p-6 flex-grow overflow-y-auto">
                        {/* PASS HOTSPOTS PROP TO MapDisplay */}
                        <MapDisplay alerts={alerts} hotspots={hotspots} /> 
                        <AlertsSection alerts={alerts} onViewAlert={setSelectedAlert} />
                    </div>
                </main>
                <AlertDetailModal alert={selectedAlert} onClose={() => setSelectedAlert(null)} />
            </div>
        </div>
    );
}